# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapmakinesi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 494)
        Dialog.setSizeIncrement(QtCore.QSize(1, 1))
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 391, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)


        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")


        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 59, 391, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")




        self.btn_parantezac = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_parantezac.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_parantezac.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_parantezac.setFont(font)
        self.btn_parantezac.setObjectName("btn_parantezac")
        self.gridLayout.addWidget(self.btn_parantezac, 0, 0, 1, 1)
        self.btn_parantezac.clicked.connect(self.parantez_ac)


        self.btn_parantezkapa = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_parantezkapa.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_parantezkapa.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_parantezkapa.setFont(font)
        self.btn_parantezkapa.setObjectName("btn_parantezkapa")
        self.gridLayout.addWidget(self.btn_parantezkapa, 0, 1, 1, 1)
        self.btn_parantezkapa.clicked.connect(self.parantez_kapa)




        self.btn_yuzde = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_yuzde.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_yuzde.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_yuzde.setFont(font)
        self.btn_yuzde.setObjectName("btn_yuzde")
        self.gridLayout.addWidget(self.btn_yuzde, 0, 2, 1, 1)
        self.btn_yuzde.clicked.connect(self.yuzde)


        self.btn_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_5.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_5.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 2, 1, 1, 1)
        self.btn_5.clicked.connect(self.tus_5 )
        

        self.btn_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_1.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_1.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 3, 0, 1, 1)
        self.btn_1.clicked.connect(self.tus_1)


        self.btn_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_8.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_8.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 1, 1, 1, 1)
        self.btn_8.clicked.connect(self.tus_8)
        


        self.btn_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_7.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_7.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 1, 0, 1, 1)
        self.btn_7.clicked.connect(self.tus_7)


        self.btn_bolme = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_bolme.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_bolme.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bolme.setFont(font)
        self.btn_bolme.setObjectName("btn_bolme")
        self.gridLayout.addWidget(self.btn_bolme, 0, 3, 1, 1)
        self.btn_bolme.clicked.connect(self.bolme)


        self.btn_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_9.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_9.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 1, 2, 1, 1)
        self.btn_9.clicked.connect(self.tus_9)


        self.btn_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_4.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_4.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 2, 0, 1, 1)
        self.btn_4.clicked.connect(self.tus_4)


        self.btn_carpma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_carpma.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_carpma.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_carpma.setFont(font)
        self.btn_carpma.setObjectName("btn_carpma")
        self.gridLayout.addWidget(self.btn_carpma, 1, 3, 1, 1)
        self.btn_carpma.clicked.connect(self.carpma)


        self.btn_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_2.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_2.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 3, 1, 1, 1)
        self.btn_2.clicked.connect(self.tus_2)



        self.btn_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_6.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_6.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 2, 2, 1, 1)
        self.btn_6.clicked.connect(self.tus_6)


        self.btn_topla = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_topla.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_topla.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_topla.setFont(font)
        self.btn_topla.setObjectName("btn_topla")
        self.gridLayout.addWidget(self.btn_topla, 2, 3, 1, 1)
        self.btn_topla.clicked.connect(self.topla)


        self.btn_cikar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_cikar.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_cikar.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikar.setFont(font)
        self.btn_cikar.setObjectName("btn_cikar")
        self.gridLayout.addWidget(self.btn_cikar, 3, 3, 1, 1)
        self.btn_cikar.clicked.connect(self.cikarma)



        self.btn_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_3.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_3.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 3, 2, 1, 1)
        self.btn_3.clicked.connect(self.tus_3)


        self.btn_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_0.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_0.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 4, 1, 1, 1)
        self.btn_0.clicked.connect(self.tus_0)


        self.btn_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_clear.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_clear.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 4, 0, 1, 1)
        self.btn_clear.clicked.connect(self.silme)



        self.btn_00 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_00.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_00.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_00.setFont(font)
        self.btn_00.setObjectName("btn_00")
        self.gridLayout.addWidget(self.btn_00, 4, 2, 1, 1)
        self.btn_00.clicked.connect(self.tus_00)


        self.btn_esit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_esit.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_esit.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_esit.setFont(font)
        self.btn_esit.setObjectName("btn_esit")
        self.gridLayout.addWidget(self.btn_esit, 4, 3, 1, 1)
        self.btn_esit.clicked.connect(self.esitlik)



        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 470, 71, 20))
        self.label.setSizeIncrement(QtCore.QSize(1, 1))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        #Labels
        Dialog.setWindowTitle(_translate("Dialog", "Hesap Makinesi"))
        self.label.setText(_translate("Dialog", "Made by FMT"))
        self.lineEdit.setText(_translate("Dialog", ""))
        #Numbers
        self.btn_1.setText(_translate("Dialog", "1"))
        self.btn_2.setText(_translate("Dialog", "2")) 
        self.btn_3.setText(_translate("Dialog", "3"))
        self.btn_4.setText(_translate("Dialog", "4"))
        self.btn_5.setText(_translate("Dialog", "5"))
        self.btn_6.setText(_translate("Dialog", "6"))
        self.btn_7.setText(_translate("Dialog", "7"))
        self.btn_8.setText(_translate("Dialog", "8"))
        self.btn_9.setText(_translate("Dialog", "9"))
        self.btn_0.setText(_translate("Dialog", "0"))
        self.btn_00.setText(_translate("Dialog", "00"))
        #Symbols
        self.btn_parantezkapa.setText(_translate("Dialog", ")"))
        self.btn_parantezac.setText(_translate("Dialog", "("))
        self.btn_esit.setText(_translate("Dialog", "="))
        self.btn_clear.setText(_translate("Dialog", "C"))
        #calculations
        self.btn_yuzde.setText(_translate("Dialog", "%"))
        self.btn_bolme.setText(_translate("Dialog", "/"))
        self.btn_carpma.setText(_translate("Dialog", "X"))  
        self.btn_topla.setText(_translate("Dialog", "+"))
        self.btn_cikar.setText(_translate("Dialog", "-"))


    def tus_1(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "1"
        self.lineEdit.setText(icerik)

    def tus_2(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "2"
        self.lineEdit.setText(icerik)

    def tus_3(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "3"
        self.lineEdit.setText(icerik)

    def tus_4(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "4"
        self.lineEdit.setText(icerik)

    def tus_5(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "5"
        self.lineEdit.setText(icerik)

    def tus_6(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "6"
        self.lineEdit.setText(icerik)

    def tus_7(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "7"
        self.lineEdit.setText(icerik)

    def tus_8(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "8"
        self.lineEdit.setText(icerik)

    def tus_9(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "9"
        self.lineEdit.setText(icerik)

    def tus_0(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "0"
        self.lineEdit.setText(icerik)

    def tus_00(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "00"
        self.lineEdit.setText(icerik)

    def parantez_ac(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "("
        self.lineEdit.setText(icerik)

    def parantez_kapa(self):
        icerik = self.lineEdit.text()
        icerik = icerik + ")"
        self.lineEdit.setText(icerik)
 
    def silme(self):
        self.lineEdit.setText("")
        


    def topla(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "+"
        self.lineEdit.setText(icerik)

    def cikarma(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "-"
        self.lineEdit.setText(icerik)

    def carpma(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "*"
        self.lineEdit.setText(icerik)

    def bolme(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "/"
        self.lineEdit.setText(icerik)

    def esitlik(self):
        icerik = self.lineEdit.text()
        try:
            if "%" in icerik:
                icerik = icerik.strip("%")
                cevap = int(icerik) / 100
            else:
                cevap = eval(icerik)
            self.lineEdit.setText(str(cevap))
        except:
            self.lineEdit.setText("Hatalı Girdiniz")    

    def yuzde(self):
        icerik = self.lineEdit.text()
        icerik = icerik + "%"
        self.lineEdit.setText(icerik)










        
        
        
        
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
